# Derived from official mysql image (our base image)
FROM mysql

# Add a database
ENV MYSQL_DATABASE aquarium
#COPY mysqldump.sql /home/.
#COPY ./sqlScripts/* /home/. 
#:RUN ./home/aquaval.sql
#RUN mysql -u root -p"wutZ25Ba" aquarium</home/mysqldump.sql 

